In [6]:
#NUMPY Tutorial
import numpy as np
x=np.array([1,2,3,4])
y=[1,2,3,4,5]

print(y)
print(type(y))

print(x)
print(type(x))


[1, 2, 3, 4, 5]
<class 'list'>
[1 2 3 4]
<class 'numpy.ndarray'>


In [9]:
%timeit [j**4 for j in range(1,8)]

3.84 µs ± 81 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [1]:
import numpy as np

%timeit np.arange(1,9)**4

3.8 µs ± 59.6 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


# Array

In [2]:
l=[]
for i in range(1,5):
    int_1=input("enter:")
    l.append(int_1)
print(np.array(l))

enter:12
enter:23
enter:12
enter:42
['12' '23' '12' '42']


# Dimensions of array

In [6]:
ar1=np.array([[1,2,3,4],[1,5,6,8]])
print(ar1)
print(ar1.ndim)
ar2=np.array([[[1,2,3,4],[1,5,6,8],[2,3,4,5]]])
print(ar2)
print(ar2.ndim)

[[1 2 3 4]
 [1 5 6 8]]
2
[[[1 2 3 4]
  [1 5 6 8]
  [2 3 4 5]]]
3


# arn=np.array([1,2,3,4],ndmin=10)
print(arn)
print(arn.ndim)

ar_zero=np.zeros(10)
ar_zero1=np.zeros((3,4))#3*4 2d array
print(ar_zero)
print(ar_zero1)


ar_one=np.ones((4,4))
print(ar_one)

print()
ar_em=np.empty(4)
print(ar_em)

# Range
ar_rn=np.arange(4)
print(ar_rn)

#diagonal elem 1
ar_dig1=np.eye(3,3)
print(ar_dig1)

#lineSpace
ar_lin=np.linspace(3,10,num=5)#gap=(10-3)/(5-1)
print(ar_lin)


# Array Using Random Numbers

In [80]:
rand_array=np.random.rand(2,2)
print(rand_array)
print()
rand_array1=np.random.randn(2,2)#numbers close to zero
print(rand_array1)
print()
rand_array2=np.random.ranf((2,2))# half open interval [0.0,1.0)
print(rand_array2)
print()
rand_array3=np.random.randint(5,10,10)
print(rand_array3)

[[0.01205851 0.34766556]
 [0.74220871 0.33513911]]

[[ 0.31484089  1.16993452]
 [-0.44661669  0.4561517 ]]

[[0.38274992 0.00881303]
 [0.30983337 0.3027787 ]]

[6 9 7 6 6 6 9 5 6 9]


# DataTypes in NumPy Arrays